#!/usr/bin/env bash
# This script manages manage_my_process daemon

start_process() {
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop_process() {
    if [ -f /var/run/my_process.pid ]; then
        kill "$(cat /var/run/my_process.pid)"
        rm -f /var/run/my_process.pid
    fi
    echo "manage_my_process stopped"
}

silent_start() {
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
}

silent_stop() {
    if [ -f /var/run/my_process.pid ]; then
        kill "$(cat /var/run/my_process.pid)"
        rm -f /var/run/my_process.pid
    fi
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        silent_stop
        silent_start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
